export const CSRF: Record<string, string>;
export interface Outcome { kind: string; tone: "good" | "warn" | "bad" | "neutral"; text: string; approvalId?: string }
export function writeOutcome(httpStatus: number, body: any): Outcome;
export function approvalOutcome(httpStatus: number, body: any, decision: "approve" | "deny"): { tone: string; done: boolean; text: string };
export function progressLabel(progress: number | null | undefined): string;
export function countdown(expiresAtIso: string, nowMs: number): string;
export function sectionNotices(ctx: any): { section: string; kind: "withheld" | "unavailable"; text: string }[];
export function memoryLine(m: any): { label: string; text: string; guess: boolean };
export function learningLine(t: any): string;
export function riskLabel(risk: string): string;
export function formatWhen(iso: string, timeZone?: string): string;
export const GRADES: { value: number; label: string }[];
export function listFrom(httpStatus: number, body: any): any[] | null;
export const HORIZONS: { value: string; label: string }[];
export function statusLabel(s: string): string;
export function projectTransitions(status: string): { to: string; label: string }[];
export function questTransitions(status: string): { action: string; label: string; ask?: "reason" | "note" }[];
export function taskTransitions(status: string): { action: string; label: string }[];
export function isTerminal(kind: string, status: string): boolean;
export function dateToInstant(value: string): string | null;
export function formatDateOnly(iso: string): string;
export function buildBody(values: Record<string, unknown>, dateFields?: string[]): { body: Record<string, unknown>; invalid: string[] };
export function taskCountsLine(c: { open?: number; done?: number; cancelled?: number } | undefined): string;
export function lifeOutcome(httpStatus: number, body: any): Outcome;
export function linkablePeople(all?: any[], linked?: any[]): any[];
export function parseRoute(hash: string): { view: "today" | "life" | "project" | "decisions" | "decision"; id?: string };
export const LIMITS: { options: { min: number; max: number }; evidence: number };
export const EVIDENCE_KINDS: { value: string; label: string }[];
export function decisionStatus(d: any, nowMs: number): { kind: "superseded" | "reviewed" | "due" | "waiting" | "recorded"; label: string };
export function canSupersede(d: any): boolean;
export function canReview(d: any): boolean;
export function buildDecisionBody(values: Record<string, unknown>, options?: { label?: string; pros?: string; cons?: string }[], chosen?: number | null, evidence?: { kind: string; refId?: string; note?: string }[], supersedesId?: string | null): { body: Record<string, unknown>; errors: string[] };
export function evidenceTag(kind: string): string;
export function resultLine(r: { statement: string; value?: number | null; unit?: string | null }): string;
export function pickerRow(kind: string, hit: any): { refId: string; title: string; sub: string };
export function withSuperseded(list: any[] | undefined): any[];
export function buildResultBody(values: Record<string, any>, subjectId: string): { body: Record<string, unknown>; errors: string[] };
export const HYPOTHESIS_LABELS: Record<string, string>;
export function hypothesisLabel(s: string): string;
export const HYPOTHESIS_ORDER: string[];
export function isClosedExperiment(s: string): boolean;
export const STANCES: { value: string; label: string }[];
export function stanceLabel(s: string): string;
export function evidenceKindLabel(link: any): string;
export function evidenceText(link: any): string;
export function evidenceGroups(links: any[]): { value: string; label: string; items: any[] }[];
export function stateHeading(state: any, index: number, total: number): string;
export function metricReadingLine(m: any): string;
export function buildStateBody(aspirationId: string, values: Record<string, string>, evidence: { sourceKind: string; sourceId: string; stance: string }[]): { body: any; errors: string[] };
export const CAPTURE_TYPE_LABELS: Record<string, string>;
export function captureTypeLabel(t: string): string;
export function captureCanSave(item: any): boolean;
export function captureStatusLabel(status: string): string;
export function captureOutcomeLabel(status: string): string;
export function buildCaptureConfirmBody(checkedIndexes: number[]): { accept: number[] };
export const MEMORY_TYPE_LABELS: Record<string, string>;
export function memoryTypeLabel(t: string): string;
export const MEMORY_FILTERS: string[];
export function memoryStatusLabel(s: string): string;
export function provenanceLabel(p: string): string;
export function canConfirmMemory(m: any): boolean;
export function canRetractMemory(m: any): boolean;
export function loopHref(ref: { type: string; id: string } | null): string | null;
export const LOOP_GROUPS: { key: string; label: string }[];
export function badgeProgress(b: { earned: boolean; have: number; need: number }): string;
export function streakLine(s: any): string;
export const ROUTINE_KINDS: { value: string; label: string }[];
export function routineKindLabel(k: string): string;
export const WEEKDAYS: { value: number; label: string }[];
export function describeRoutineDays(days: number[]): string;
export function routineStateLabel(item: any): string;
export function canCheckRoutine(item: any): boolean;
export function buildRoutineBody(values: Record<string, string>, days: number[]): { body: any; errors: string[] };
