export const CSRF: Record<string, string>;
export interface Outcome { kind: string; tone: "good" | "warn" | "bad" | "neutral"; text: string; approvalId?: string }
export function writeOutcome(httpStatus: number, body: any): Outcome;
export function approvalOutcome(httpStatus: number, body: any, decision: "approve" | "deny"): { tone: string; done: boolean; text: string };
export function progressLabel(progress: number | null | undefined): string;
export function countdown(expiresAtIso: string, nowMs: number): string;
export function sectionNotices(ctx: any): { section: string; kind: "withheld" | "unavailable"; text: string }[];
export function memoryLine(m: any): { label: string; text: string; guess: boolean };
export function learningLine(t: any): string;
export function riskLabel(risk: string): string;
export function formatWhen(iso: string, timeZone?: string): string;
export const GRADES: { value: number; label: string }[];
export function listFrom(httpStatus: number, body: any): any[] | null;
export const HORIZONS: { value: string; label: string }[];
export function statusLabel(s: string): string;
export function projectTransitions(status: string): { to: string; label: string }[];
export function questTransitions(status: string): { action: string; label: string; ask?: "reason" | "note" }[];
export function taskTransitions(status: string): { action: string; label: string }[];
export function isTerminal(kind: string, status: string): boolean;
export function dateToInstant(value: string): string | null;
export function formatDateOnly(iso: string): string;
export function buildBody(values: Record<string, unknown>, dateFields?: string[]): { body: Record<string, unknown>; invalid: string[] };
export function taskCountsLine(c: { open?: number; done?: number; cancelled?: number } | undefined): string;
export function lifeOutcome(httpStatus: number, body: any): Outcome;
export function linkablePeople(all?: any[], linked?: any[]): any[];
export function parseRoute(hash: string): { view: "today" | "life" | "project"; id?: string };
